#ifndef _EVENTDEFINE_H_
#define _EVENTDEFINE_H_

#pragma once

#include "../gamed/event/MessageDef.h"

#ifndef EVENT_BASE
#define EVENT_BASE 0

enum WEB_HTTP_REQUEST_TYPE
{
	WEBREQ_Unknow = 0,
	WEBREQ_CountryRank,
	WEBREQ_ChickenRank,
	WEBREQ_FamousPersonHall,
	WEBREQ_TomorrowStar = 4,
	WEBREQ_TomorrowRank = 5,
	WEBREQ_ServerStat = 6,
	WEBREQ_Cathectic = 7,
	WEBREQ_SiteCreditQZone = 8,
	WEBREQ_SiteCreditQHall = 9,
};

enum EVENT_DEFINE
{
	EVENT_UPDATE_WORKING_STATUS	= EVENT_BASE + 1,
	EVENT_USER_LOGIN,
	EVENT_USER_LOGOUT,
	EVENT_USER_AUTH,
	EVENT_TIMER,
	EVENT_SEND_REMOTE_USER,
	EVENT_GWG_FRIEND_REQUEST,
	EVETN_GWG_GAMESTAR_REQUEST,
	EVENT_UPDATE_FRIEND_CACHE,
	EVENT_UPDATE_STARINFO,	
	EVENT_GWG_CHECK_ATTACK,
	EVENT_STAR_STATE,	
	EVENT_USER_PRELOGIN,	//用户预加载
	EVENT_USER_BRAODCAST,
	EVENT_USER_HOURMETER_BRAODCAST,
	EVENT_USER_HOURMETER_BRAODCAST_START,
	EVENT_UPDATE_BROADCAST_ROBOT,
	EVENT_WEB_GETREGION,
	EVENT_UPDATE_PLATINFO,
	EVENT_TIMER_5_TICK,		//五分钟消息
	EVENT_LUCKY_NUM,		//幸运数字

	EVENT_GF_FIGHT_REQUEST_PVE,		//PVE请求战斗
	EVETN_G2G_GAMEHTTP_REQUEST,		//HTTP请求
	EVENT_GF_FIGHT_REQUEST_ARENA,	//竞技场请求战斗
	EVENT_COUNTRY_LITE,				//国家人数 
	EVENT_COUNTRY_USERLIST,			//城市玩家列表
	EVENT_LOADUSER_4LITE,			//保存玩家lite数据
	EVENT_GF_COUNTRY_FIGHT,			//国战请求
	EVENT_COUNTRY_FORCECHGCITY,		//强制切换城市
	EVENT_COUNTRY_CHECKCAPTURECITY,	//判断城市是否被攻占
	EVENT_SENDCOUNTRY_REPORT,		//发送国家战报
	EVENT_UPDATE_COUNTRY_USER,		//向国家服务器更新玩家信息
	EVENT_COSTGIFT_INVITE_FRD,		//消费礼物plat返回数据
	EVENT_ARENA_USERLIST,			//竞技场玩家列表
	EVENT_INVITED_FRD_LV_GIFT,		//邀请好友等级奖励
	EVENT_CALLBACKFRRD_GIFT,
	EVENT_WEB_QPOINT_SHOP,
	EVENT_REPAIR_BASE,
	EVENT_PVE_RECORD_REQUEST,		//查看PVE战报请求
	EVENT_ARENA_RECORD_REQUEST,		//查看竞技场战报请求
	EVENT_COUNTRY_BLOODBTL_INFO,	//血战信息 
	EVENT_COUNTRY_TIMER,			//国家计时器
	EVENT_COUNTRY_BLOODBTL_BALLANCE,//血战结算
	EVENT_COUNTRY_BLOODBTL_OVER,	//血战结束
	EVENT_COUNTRY_BLOODBTL_REWARD,	//血战胜利方奖励
	EVENT_COUNTRY_BLOODBTL_LAUNCHREWARD,//血战发起者胜利奖励
	EVENT_WEB_QPOINT_SHOP_COUNT,

	EVENT_WORLDARENA_RECORD_REQUEST,	//查看世界竞技场战报请求
	EVENT_GF_FIGHT_REQUEST_WORLDARENA,	//世界竞技场请求战斗
	EVENT_WORLDARENA_USERLIST,	//世界竞技场玩家列表
	EVENT_UPDATE_COUNTRY_WORLDARENA,	//更新竞技场
	EVENT_GUILD_USERLIST,	//工会玩家列表
	EVENT_GUILD_BELEADER,	//工会将其改为会长
	EVENT_GUILD_STAT,		//工会统计
	EVENT_OFFICER_USERLIST,	//官员用户信息列表
	EVENT_OFFICER_RIGHT_USE_INFO,	//官员使用权限信息
	EVENT_OFFICER_RIGHT_CITY_ALL,	//所有城市的官员信息
	EVENT_COUNTRY_USER_LITE,				//国家用户信息变化


	EVENT_WEB_ADDICTION, //防沉迷信息
	EVENT_FRIEND_GIFT,

	EVENT_GUILDBTL_CACU,	//工会战计算
	EVENT_GUILDBTL_SEEREPORT,	//观战
	EVENT_COUNTRY_BROADCAST,	//国家发送的广播

	EVENT_WEB_CALL,

	EVENT_COUNTRY_BLOODBTL_LOSE,	//血战失败，踢回老家
	EVENT_COUNTRY_UPDATEUSERNAMEDATA,//更新玩家名字等数据

	EVENT_WEB_QQTASK,	//任务提示
	EVENT_REGION_TIMER,			//全区服务器计时器
	EVENT_REGIONARENA_RECORD_REQUEST,	//查看跨区竞技场战报请求
	EVENT_REGIONARENA_USERLIST,	        //跨区竞技场玩家列表
	EVENT_GF_FIGHT_REQUEST_REGIONARENA,	//跨区竞技场请求战斗
	EVENT_REGION_USER_LITE,				//跨区用户信息

	EVENT_WEB_ASKACROSS,	//交叉推广询问

	EVENT_GF_FIGHT_BATTLE_PVE,		//Battle请求战斗

	EVENT_INVITED_FRD_LV_GIFT_RECORD,	//邀请好友等级奖励自身记录

    EVENT_WORLDCUP_BET,                 //世界杯竞猜


	//跨服国战相关
	EVENT_REGION_COUNTRY_LITE,				//国家人数 
	EVENT_REGION_COUNTRY_USERLIST,			//城市玩家列表
	EVENT_REGION_GF_COUNTRY_FIGHT,			//国战请求
	EVENT_REGION_COUNTRY_FORCECHGCITY,		//强制切换城市
	EVENT_REGION_COUNTRY_CHECKCAPTURECITY,	//判断城市是否被攻占
	EVENT_REGION_SENDCOUNTRY_REPORT,		//发送国家战报
	EVENT_REGION_UPDATE_COUNTRY_USER,		//向国家服务器更新玩家信息
	EVENT_REGION_COUNTRY_USER_LITE,			//国家用户信息变化

	EVENT_REGIONCOUNTRY_TIMER,			//全区跨服国战计时器
	EVENT_REGION_COUNTRY_FIGHT_RESULT,	//跨服国战结果

    EVENT_OPENSNS_GIFT,                 //开放平台礼包

    EVENT_VALENTINES_DAY_GIFT,          //情人节礼物

	EVENT_HEROARENA_RECORD_REQUEST,	    //查看英雄竞技场战报请求
	EVENT_GF_FIGHT_REQUEST_HEROARENA,	//英雄竞技场请求战斗
	EVENT_HEROARENA_USERLIST,	        //英雄竞技场玩家列表

    EVENT_RENT_WEAPONCOMPONENT,         //租用武器配件
	EVENT_GVGBTL_CACU,	//GVG计算
	EVENT_GVGBTL_SEEREPORT,	//GVG观战

	EVENT_FIGHT_TIMER,			//战斗服务器计时器

	EVENT_GVG_STAT,		//GVG统计

	EVENT_WPCRANK,		//武器中心探索计算
	EVENT_UPDATE_COUNTRY_WPCRANK,		//向国家服务器更新玩家信息

	EVENT_GET_IDENT_INFO,//web请求验证信息
	EVENT_PUT_IDENT_INFO,//web发送验证成功

	EVENT_GUILD_ACCUM_CONTRIBUTE,//一周内贡献值最高的
	//排行榜服务器
	EVENT_RANK_TIMER,			//国家计时器
	EVENT_RANK_ZHANGONG,		//战功排行榜
	EVENT_RANK_GETLASTDAY_ZHANGONG,//

	EVENT_COUNTRYCHAT_BROAD,	//国战聊天,广播一条

    EVNT_REDENVELOPE_RANK,				//红包排行榜

    EVENT_BOSSBTL_LITE,				//BOSS战战斗记录

	EVENT_HALL_QUERY_USER_INFO,			//idip大厅查询用户信息
	EVENT_HALL_QUERY_USER_CREDIT,		//idip查询用户充值总额
	EVENT_HALL_QUERY_USER_COST,			//idip查询用户花费勋章总额
	EVENT_HALL_ADD_ITEM,				//idip发简单道具
	//管理员命令
	EVENT_ADMIN = 2048,
	EVENT_ADMIN_PROFILE,
	EVENT_ADMIN_ADDEXP,
	EVENT_ADMIN_ADDCASH,
	EVENT_ADMIN_SETLEVEL,
	EVENT_ADMIN_BANCHAT,
	EVENT_ADMIN_BANLOGIN,
	EVENT_ADMIN_RELOAD,
	EVENT_ADMIN_CANATTACK,
	EVENT_WEB_INVITEFRIEND,
	EVENT_WEB_SENDGIFT,
	EVENT_WEB_SENDGIFTPLATID,
	EVENT_ADMIN_BANDWGUSER,
	EVENT_ADMIN_OPT,
	EVENT_WEB_PHOTO,
	EVENT_WEB_CALLBACKFRIEND,
	EVENT_WEB_CALLBACKFRIENDPLATID,
	EVENT_ADMIN_ADDHONOR,
	EVENT_WEG_GIFT,
	EVENT_WEB_GIFTSEND,
	EVENT_WEB_GIFT2FRD,
	EVENT_WEB_BROADCAST,
	EVENT_ADMIN_CLEARDEFENSE,
	EVENT_WEB_SETALARMCLOCK,
	EVENT_ADMIN_SETNEWCOMERGIFT,
	EVENT_ADMIN_SETCONTINUELANDDAY,
	EVENT_WEB_INVITEFRIEND_PLAT,
	EVENT_ADMIN_SETPLATINVITEID,
	EVENT_WEB_YELLOWGUNGOLD,
	EVENT_WEB_REFRESHYELLOW,
	EVENT_WEB_TXMISSIONOPERATE,
	EVENT_WEB_SHARE,
	EVENT_GET_DAILY_YELLOW_RES,
	EVENT_WEB_REFRESHYELLOW_REBATE,
	EVENT_SELF_ADDGIFTTOPLAT,
	EVENT_WEB_TRYINVITE_FRIEND,
	EVENT_ADMIN_GETBLDCNT,
	EVENT_AD_SET,
	EVENT_WEB_ADDQQPANLE,
	EVENT_ADMIN_RELOADCHICKENRANK,
	EVENT_WEB_REQUEST_LEVEL,
	EVENT_ADMIN_ADDGUILDBTLREWARD,
	EVENT_ADMIN_RESETWHOLECOUNTRY,
	EVENT_ADMIN_GVELIST,
    EVENT_ADMIN_RESETGUILDPKSCORE,
    EVENT_ADMIN_OUTPUTGUILDUSERLIST,
	EVENT_ADMIN_SITECREDITRELOAD,

	EVENT_QUERY_STAR_INFO,
};

enum Status_UpdateWorkingStatus 
{
	UpdateWorkingStatus_GW_Disconn = 0,
	UpdateWorkingStatus_WG_Disconn,
	UpdateWorkingStatus_GW_Conn,
	UpdateWorkingStatus_WG_Sync,
	UpdateWorkingStatus_GW_Sync,
	UpdateWorkingStatus_WG_Fin,

	UpdateWorkingStatus_GH_Disconn,
	UpdateWorkingStatus_HG_Disconn,
	UpdateWorkingStatus_GH_Conn,
	UpdateWorkingStatus_HG_Sync,
	UpdateWorkingStatus_GH_Sync,
	UpdateWorkingStatus_HG_Fin,

};

enum Status_UserLogin 
{
	UserLogin_WW_Req = 0,
	UserLogin_WG_Req,
	UserLogin_GW_Rsp,

	UserLogin_GP_Req,
	UserLogin_PG_Rsp,

	UserLogin_GCo_Req,
	UserLogin_CoG_Rsp,
};

enum Status_NormalStats
{
	Status_Normal_WW_Req = 0,
	Status_Normal_Game,
	Status_Normal_To_World,
	Status_Normal_Logic_Game,
	Status_Normal_Back_World,
	Status_Normal_Back_Game,

	Status_Normal_To_Star,
	Status_Normal_Star_Back,
	Status_Normal_StarSlf,

	Status_Normal_WG_UPBROADCAST,
	
	Status_World_To_Plat,
	Status_Plat_To_World,
	Status_Game_To_Plat,
	Status_Plat_To_Game,

	Status_Normal_To_Fight,
	Status_Normal_Back_Fight,

	Status_Game_To_Country,
	Status_Country_To_Game,

	Status_UserLite_To_Game,

	Status_Game_To_Region,
	Status_Region_To_Game,

    Status_Game_To_World,

	Status_Game_To_Rank,
	Status_Rank_To_Game,

	Status_Game_To_Stat,
	Status_Stat_To_Game,

	Status_Game_To_Monitor = 100,
	Status_Monitor_To_Game,

};

enum EventState
{
	EVENTSTATE_CG = 0,
	EVENTSTATE_CGW,
	EVENTSTATE_CGWG,
	EVENTSTATE_CGWGW,
	EVENTSTATE_CGWGWG,
};

enum Status_UserAuth 
{
	UserAuth_CG_Req = 0,
	UserAuth_GC_Rsp
};

enum Status_SendRemoteUser 
{
	SendRemoteUser_GW_Req = 0,
	SendRemoteUser_WG_Req
};

enum Status_Admin 
{
	Admin_AG_Req = 0,
	Admin_GW_Req,
	Admin_WG_Req,
	Admin_GW_Rsp,
	Admin_WG_Rsp,
	Admin_GA_Rsp,
	Admin_WW_Req,
	Admin_CG_Rsq,
};

#endif

#endif
