#ifndef _EVENTDEFINE_H_
#define _EVENTDEFINE_H_

#pragma once

#include "../gamed/event/MessageDef.h"

#ifndef EVENT_BASE
#define EVENT_BASE 0

enum EVENT_DEFINE
{
	EVENT_UPDATE_WORKING_STATUS	= EVENT_BASE + 1,
    EVENT_USER_REGIST,
	EVENT_USER_LOGIN,
	EVENT_USER_AUTH,
    EVENT_USER_DISCONNECT,
	EVENT_USER_BIND,
	EVENT_USER_RECHARGE,
	EVENT_PLAYER_INFO,
	EVENT_STARTSERVER,
	EVENT_TIMER,
	EVENT_USER_LUCKYGODDESS,
	EVENT_USER_INVITERSREWARD,
	EVENT_RECHARGE_REWARD_CHECK,
    EVENT_GM,
    EVENT_TICKARENA,
    EVENT_TICKQUIZ,
    EVENT_TICKQUIZAWARD,
	EVENT_TICKRICHESTAWARD,
    EVENT_TICKGUARD,
    EVENT_TICKPLAYERNAME,
    EVENT_TICKSTAGE,
    EVENT_TICKADVSTAGE,
    EVENT_TICKCAMP,
	EVENT_TICKGUILD,
	EVENT_TICKGLOBAL,
	EVENT_TICKROBBERY,
	EVENT_TICKRICHEST,
	EVENT_GUILDDELETE,
	EVENT_TICKGHOSTSHIP,
	EVENT_TICKGHOSTSHIPAWARD,
	EVENT_TICKPLAYERBASEINFO,
	EVENT_TICKLIMITSHIP,
	EVENT_TICKLIMITSHIPAWARD,
	EVENT_TICKFRIENDSYSBACKSENDELEC,
	EVENT_TICKCHAT,
	EVENT_TICKCAMPBATTLE,
	EVENT_TICKCAMPBATTLE_AWARD,
	EVENT_TICKCAMP_NPC,
	EVENT_TICKBROADCAST,
	EVNET_TICKAUTOCHANGECHIEF,
	EVENT_TICKGUILDSENDMAIL,
	EVENT_WORLD_BROADCAST,
	EVENT_WORLD_CENTERCAMPBATTLE_AWARD,
	EVENT_TICKCENTERCAMPBATTLE,
    EVENT_TICK_ONE_ARMED_BANDIT,
    EVENT_TICK_ONE_ARMED_BANDIT_TOP_AWARD,
    EVENT_TICK_WORLD_GLOBAL_DATA,
    EVENT_CHALLENGE_SYNC_TACTIC_INFO,
    EVNET_CHALLENGE_REVENGE,
    EVENT_CHALLENGE_REWARD,
	EVENT_TICKLIMITCAPTAINAWARD,
	EVENT_TICKLIMITCAPTAIN,
	EVENT_TICKLIMITCAPTAIN2,
    EVENT_CHALLENGE_LOGIN,
    EVENT_CHALLENGE_BROADCAST,
	EVENT_TICKGUILDBATTLE,
	EVENT_TICKGUILDBATTLE_AWARD,
	EVENT_TICK_GOLDISLAND,
	EVENT_GOLDISLAND_REWARD,
	EVENT_TICKARMADA,
	EVENT_TICKARMADATOPAWARD,
	EVENT_TICKVALENTINE,
	EVENT_TICKVALENTINEAWARD,
	EVENT_TICKGLOBALARENA,
	EVENT_TICKGLOBALARENABATTLE,
	EVENT_TICKALLGLOBALARENA,
	EVENT_SYNGLOBALARENATOALLARENA,
	EVENT_GETALLALOBALCHAMPTIONAWARD,
	EVENT_TICKGOLDACTIVE,
	EVENT_GOLDACTIVE_AWARD,
	EVENT_CAMPBATTLE_AI,
	EVENT_TICK_WORLD_STAGE_RANK,
	EVENT_SYN_TACTICINFO_STAGE_RANK,
	EVENT_GET_ENEMYLIST_FROM_STAGE_RANK,
	EVENT_ADD_ALLGLOBALARENACHAMPTION,

	EVENT_TUANGOU_JOIN_REQUEST,	//团购报名
	EVENT_TUANGOU_JOIN_INFOMAT,	//团购获取数据
	EVENT_TUANGOU_NUMBER_REQUEST,//团购获取人数
	EVENT_TUANGOU_CLEAR_VERSION,
	EVENT_TUANGOU_SEND_GIFT,	//团购发送奖励
	EVENT_SAVE_WORLD_TUANGOUMODUL_DATA,
	EVENT_SAVE_GMAES_TUANGOUMODUL_DATA,

	EVENT_GUILDBATTLE_BUSYHANDLER,

	EVENT_SEND_GOLDISLAND_WIN_MAIL,	//发送守岛失败者邮件
	EVENT_TICKRANKING, // 排行榜保存
	EVENT_TICKGOLDACTIVE2,
	EVENT_TICKGLOBALGUILDBATTLE,
	EVENT_TICKGLOBALGUILDBATTLEGAME,
	EVENT_GLOBALGUILDBATTLEGAME,
	EVENT_TICKGLOBALGUILDPROMOTEBATTLE,
	EVENT_GETGLOBALGUILDCHAMPTIONAWARD,

};

enum Status_UpdateWorkingStatus 
{
	UpdateWorkingStatus_GW_Disconn = 0,
	UpdateWorkingStatus_WG_Disconn,
	UpdateWorkingStatus_GW_Conn,
	UpdateWorkingStatus_WG_Sync,
	UpdateWorkingStatus_GW_Sync,
	UpdateWorkingStatus_WG_Fin,
};

enum EventState
{
    Client_to_Game = 1,
    Game_to_Client,
    Game_to_Self,

    Game_to_Game,
    Game_to_World,
    Game_to_Web,

    World_to_Game,
    World_to_Web,
	World_to_Self,

    Web_To_World,
    Web_To_Game,
};

#endif

#endif
