// Generated by the protocol buffer compiler.  DO NOT EDIT!

#ifndef PROTOBUF_RceObtainRandomTargets_2eproto__INCLUDED
#define PROTOBUF_RceObtainRandomTargets_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_RceObtainRandomTargets_2eproto();
void protobuf_AssignDesc_RceObtainRandomTargets_2eproto();
void protobuf_ShutdownFile_RceObtainRandomTargets_2eproto();

class RceObtainRandomTargets;

// ===================================================================

class RceObtainRandomTargets : public ::google::protobuf::Message {
 public:
  RceObtainRandomTargets();
  virtual ~RceObtainRandomTargets();
  
  RceObtainRandomTargets(const RceObtainRandomTargets& from);
  
  inline RceObtainRandomTargets& operator=(const RceObtainRandomTargets& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const RceObtainRandomTargets& default_instance();
  void Swap(RceObtainRandomTargets* other);
  
  // implements Message ----------------------------------------------
  
  RceObtainRandomTargets* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RceObtainRandomTargets& from);
  void MergeFrom(const RceObtainRandomTargets& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const { _cached_size_ = size; }
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 starId = 1;
  inline bool has_starid() const;
  inline void clear_starid();
  static const int kStarIdFieldNumber = 1;
  inline ::google::protobuf::int32 starid() const;
  inline void set_starid(::google::protobuf::int32 value);
  
  // optional string planetId = 2;
  inline bool has_planetid() const;
  inline void clear_planetid();
  static const int kPlanetIdFieldNumber = 2;
  inline const ::std::string& planetid() const;
  inline void set_planetid(const ::std::string& value);
  inline void set_planetid(const char* value);
  inline void set_planetid(const char* value, size_t size);
  inline ::std::string* mutable_planetid();
  
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int32 starid_;
  ::std::string* planetid_;
  static const ::std::string _default_planetid_;
  friend void  protobuf_AddDesc_RceObtainRandomTargets_2eproto();
  friend void protobuf_AssignDesc_RceObtainRandomTargets_2eproto();
  friend void protobuf_ShutdownFile_RceObtainRandomTargets_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static RceObtainRandomTargets* default_instance_;
};
// ===================================================================


// ===================================================================


// ===================================================================

// RceObtainRandomTargets

// optional int32 starId = 1;
inline bool RceObtainRandomTargets::has_starid() const {
  return _has_bit(0);
}
inline void RceObtainRandomTargets::clear_starid() {
  starid_ = 0;
  _clear_bit(0);
}
inline ::google::protobuf::int32 RceObtainRandomTargets::starid() const {
  return starid_;
}
inline void RceObtainRandomTargets::set_starid(::google::protobuf::int32 value) {
  _set_bit(0);
  starid_ = value;
}

// optional string planetId = 2;
inline bool RceObtainRandomTargets::has_planetid() const {
  return _has_bit(1);
}
inline void RceObtainRandomTargets::clear_planetid() {
  if (planetid_ != &_default_planetid_) {
    planetid_->clear();
  }
  _clear_bit(1);
}
inline const ::std::string& RceObtainRandomTargets::planetid() const {
  return *planetid_;
}
inline void RceObtainRandomTargets::set_planetid(const ::std::string& value) {
  _set_bit(1);
  if (planetid_ == &_default_planetid_) {
    planetid_ = new ::std::string;
  }
  planetid_->assign(value);
}
inline void RceObtainRandomTargets::set_planetid(const char* value) {
  _set_bit(1);
  if (planetid_ == &_default_planetid_) {
    planetid_ = new ::std::string;
  }
  planetid_->assign(value);
}
inline void RceObtainRandomTargets::set_planetid(const char* value, size_t size) {
  _set_bit(1);
  if (planetid_ == &_default_planetid_) {
    planetid_ = new ::std::string;
  }
  planetid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RceObtainRandomTargets::mutable_planetid() {
  _set_bit(1);
  if (planetid_ == &_default_planetid_) {
    planetid_ = new ::std::string;
  }
  return planetid_;
}


#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

#endif  // PROTOBUF_RceObtainRandomTargets_2eproto__INCLUDED
