#ifndef _AUTOEVENTHEAD_H_
#define _AUTOEVENTHEAD_H_
#pragma once
//该文件为使用工具自动生成，请不要在文件中修改，如需要修改，请与sskylin联系。
#include "RceCustomizedActivityHandle.h"
#include "RceLoginHandle.h"
#include "RceObtainAttackerListHandle.h"
#include "RceObtainBattleReplayHandle.h"
#include "RceObtainCustomizerHandle.h"
#include "RceObtainMessagesListHandle.h"
#include "RceObtainNeighborsListHandle.h"
#include "RceObtainNpcListHandle.h"
#include "RceObtainSocialItemsHandle.h"
#include "RceObtainSocialUserInfoHandle.h"
#include "RceObtainUniverseHandle.h"
#include "RceUpdateAlliancesHandle.h"
#include "RceDeployUnitsHandle.h"
#include "RceItemDamagedHandle.h"
#include "RceObtainAskForHelpHandle.h"
#include "RceObtainHangarsHelpHandle.h"
#include "RceObtainPayUrlParameHandle.h"
#include "RceObtainRandomTargetsHandle.h"
#include "RceObtainVisitHelpsHandle.h"
#include "RceOnlineRewardHandle.h"
#include "RceQueryCheckAndLockAccountIfPossibleHandle.h"
#include "RceQueryGalaxyWindowHandle.h"
#include "RceQueryReceiveWishItemHandle.h"
#include "RceQueryRefuseReceiveWishItemHandle.h"
#include "RceQuerySendWishItemHandle.h"
#include "RceQueryStarInfoHandle.h"
#include "RceQueryStarsBookmarksHandle.h"
#include "RceQueryVisitHelpsGiftUnitsOnBunkerHandle.h"
#include "RceUnitDamagedHandle.h"
#include "RceUpdateGameUnitsHandle.h"
#include "RceUpdateItemHandle.h"
#include "RceUpdateMiscHandle.h"
#include "RceUpdateMissionsHandle.h"
#include "RceUpdateProfileHandle.h"
#include "RceUpdateShipsHandle.h"
#include "RceUpdateSocialItemHandle.h"
#include "RceUpdateStarsBookmarksHandle.h"
#include "RceUpdateTargetsHandle.h"
#include "RceUpdateVisitHelpHandle.h"
#endif


