#include "LogDef.h"


static const char* LOG_CONFIG[LT_MAX*2] =
{
  //log string          is sampling
	"LogOn",            "1",
	"LogOut",           "1",
	"LogIn",			"1",
	"Register",         "1",
	"LevelUp",          "1",
	"Recharge",			"1",
	"UndoRecharge",		"0",
	"MonthCard",		"0",
	"LimitFight",		"0",
	"SetNewDay",		"0",
	"BanLogin",			"1",
	"SameName",			"1",
	"LUCKYGODDESSFORCHARGE","1",
	"INVITERSREWARD","1",
	"AddExp",			"0",
	"AddGold",			"0",
	"CostGold",			"0",
	"AddCash",			"1",
	"CostCash",			"1",
	"AddPoint",			"0",
	"CostPoint",		"0",
	"AddOil",			"0",
	"CostOil",			"0",
	"AddElectric",		"0",
	"CostElectric",		"0",
	"AddJuniorPaper",	"0",
	"CostJuniorPaper",	"0",
	"AddSeniorPaper",	"0",
	"CostSeniorPaper",	"1",
	"AddArenaPoint",	"0",
	"CostArenaPoint",	"1",
	"AddGuildPoint",	"0",
	"CostGuildPoint",	"1",
	"AddJuniorStar",	"0",
	"CostJuniorStar",	"0",
	"AddSeniorStar",	"0",
	"CostSeniorStar",	"0",
	"AddCampBattleScore", "0",
	"CostCampBattleScore", "0",
	"AddMilitaryRankHonour", "0",
	"MilitaryRankRightOption","0",
	"LuckBoxExchangePoint","0",
	"ShipFormationAdd","0",
	"ShipFormationLevelUp","0",
	"ShipFormationStarUp","0",
	"ShipFormationInit","0",
	"CostGuildBuildPoint","0",
	"CostMaterial","0",
	"AddMaterial","0",
	"CostRemouldMaterial","0",
	"AddRemouldMaterial","0",
	"AddSeikoCoin","0",
	"CostSeikoCoin","0",
	"CostMonthCardDate", "0",
	"DceAllLastID",		"0",
	"DceAutoEquipSoldier",	"0",
	"DceBattleStart",	"1",
	"DceBuy",			"1",
	"DceBuyOil",		"0",
	"DceCenterRecovery",	"0",
	"DceChargePaper",	"0",
	"DceCreateShip",	"0",
	"DceDecomposeParts",	"0",
	"DceEnterArena",	"0",
	"DceEnterGuard",	"0",
	"DceEquipParts",	"0",
	"DceGetCenterGold",	"0",
	"DceGetMailProp",	"0",
	"DceGetTactic",		"0",
	"DceGetWeakCamp",	"0",
	"DceGuardStage",	"0",
	"DceLeaveGuard",	"0",
	"DceMailList",	"0",
	"DceNewDay",	"0",
	"DceOwnedPaper",	"0",
	"DcePaperList",	"0",
	"DcePaperPieceList",	"0",
	"DcePartsList",	"0",
	"DcePropList",	"0",
	"DceQuestionAnswer",	"1",
	"DceQuestionList",	"0",
	"DceQuestionRank",	"0",
	"DceRemouldParts",	"0",
	"DceRemouldShip",	"0",
	"DceRenameShip",	"0",
	"DceResetStageCount",	"1",
	"DceRetireShip",	"0",
	"DceSalePaper",	"0",
	"DceSaveTrain",	"0",
	"DceScienceList",	"0",
	"DceScoutSoldier",	"0",
	"DceSellProp",	"0",
	"DceSetCaption",	"0",
	"DceSetRole",	"1",
	"DceSetSoldier",	"0",
	"DceSetTactic",	"0",
	"DceShipList",	"0",
	"DceShopData",	"0",
	"DceSoldierList",	"0",
	"DceSpy",	"1",
	"DceSpyData",	"0",
	"DceStageList",	"0",
	"DceTrain",	"0",
	"DceUnEquipParts",	"0",
	"DceUpgradeBuild",	"0",
	"DceUpgradeParts",	"0",
	"DceUpgradeScience",	"0",
	"DceUpgradeShip",	"0",
	"DceUpgradeSkill",	"0",
	"DceUseProp",	"0",
	"DceUserData",	"0",
	"DceActivity",  "0",
	"DceActivityData",	"0",
	"DceArenaExchange",	"1",
	"DceGuideStep",		"1",
	"DceAccBind",		"0",
	"DceGuildApply",	"0",
	"DceGuildCancelApply", "0",
	"DceGuildApproval",	"0",
	"DceGuildBuyGift",	"0",
	"DceGuildDemise",	"0",
	"DceGuildDismiss",	"0",
	"DceGuildDismissCancel",	"0",
	"DceGuildDonate",	"1",
	"DceGuildExpel",	"0",
	"DceGuildFireDeputy",	"0",
	"DceGuildInvite",	"0",
	"DceGuildQuit",	"0",
	"DceGuildSetDeputy","0",
	"DceCreateGuild", "0",
	"DceMonthCard", "0",
	"DceGetDayLimitFight", "0",
	"DceGuildSetMedal",	"0",
	"DceGuildUpgrade", "0",
	"DceRobberyList", "0",
	"DceComposeParts", "0",
	"DceGetMedal", "0",
	"DceGhostShip", "1",
	"DceGhostShipData", "0",
	"DceConsumeExchange", "1",
	"DceConsumeExchangeData", "0",
	"DceSevenDaysExchange", "1",
	"DceSevenDaysExchangeData", "0",
	"DceAddFriend", "0",
	"DceRefuseAddFriend", "0",
	"DceDeleteFriend", "0", 
	"DceInviteFriend", "0",
	"DceSendElectric", "0",
	"DceDrawElectric", "0",
	"DceDrawAllElectric","0",
	"DceFriendlist", "0", 
	"DceRecommandInvitedList", "0",
	"DceInvitedList", "0",
	"DceReceiveElectricList", "0",
	"DceLimitShip", "1",
	"DceRenameRole", "1",
	"DceGetAward", "0",
	"DceLuckyWheelData","0",
	"DceLuckyWheel","0",
	"DceResetGuard", "0",
	"DceBuyGuard", "0",
	"DceSoul", "1",
	"DceSoulEat", "0",
	"DceEquipSoul", "0",
	"DceUnEquipSoul", "0",
	"DceCampBattleMove", "0",
	"DceClearCampBattleCD", "0",
	"DceCampBattleData", "0",
	"DceMisteryShopRefresh", "0",
	"DceCampBattleResult", "0",
	"DceCampBattleEnter", "0",
	"DceLuckyGoddessData","0",
	"DceLuckyGoddessForFree","1",
	"DceSendMail","0",
	"DceBlackListOpt", "0",
	"DceMilitaryRankReward","0",
	"DceMilitaryRankInfo","0",
	"DceMilitaryRankUpgrad","0",
	"DceUserComeBack","0",
	"DceUserComeBackReward","0",
	"DceGoddessRewardData","0",
	"DceGoddessReward","1",
	"DceLuckBoxPointExchangeOpen","0",
	"DceLuckBoxPointExchange","1",
	"DceLoginPokerAction","1",
	"DceLoginPokerFinal","0",
	"DceRedcutionParts","0",
	"DceCenterCampBattleMove","0",
	"DceClearCenterCampBattleCD","0",
	"DceCenterCampBattleData","0",
	"DceCenterCampBattleResult","0",
	"DceCenterCampBattleEnter","1",
	"DceCenterCampBattleRankList","0",
	"DceUsePaperPieceGift","1",
	"DceReductionPartsInfo","0",
	"DceCampBattleBuy","0",
	"DceCenterCampBattleBuy","0",
	"DceShipFormationInfo","0",
	"DceShipFormationChoose","0",
	"DceBuySpyItem","0",
	"DceUpgradeCaptain","0",
	"DcePromoteCaptain","0",
	"DceFireCaptain","0",
	"DceExchangeCaptain","0",
	"DceComposeCaptain","0",
	"DceEquipCaptain","0",
	"DceBuyRecruitItem","0",
	"DceRecruitCaptain","0",
	"DceLimitCaptainData","0",
	"DceLimitCaptain","1",
	"DceUseSuperCaptainGift","0",
	"DceBuyLimitCaptain","0",
	"DceBuyGhostShip","0",
	"DceBuyLimitShipItem", "0",
	"DceLimitShipData", "0",
	"DceCampBattleSetTrustee","0",
	"DceSuperExchangeInfo","0",
	"DceSuperExchangeItem","1",
	"DceGuildScienceList","0",
	"DceUpgradeGuildScience","0",
	"DceGuildBattleSignUp","1",
	"DceGuildBattleSignUpList","0",
	"DceGuildBattlePrepare","1",
	"DceGuildBattleRankList","0",
	"DceGuildBattleEnter","1",
	"DceGuildBattleMove","0",
	"DceClearGuildBattleCD","0",
	"DceGuildBattleBuy","0",
	"DceGuildBattleResult","0",
	"DceChangeRole","0",
	"DceGoldIslandDelayTime","0",
	"DceGoldIslandOpen","0",
	"DceGoldIslandHelp","1",
	"DceGoldIslandInviteHelp","0",
	"DceGoldIslandSearch","0",
	"DceGoldIslandOccupy","1",
	"DceGoldIslandApplyHelp","0",
	"DceGoldIslandAgreeApply","1",
	"DceGoldIslandInviteMemberList","0",
	"DceGoldIslandCancel","0",
	"DceArmadaData","0",
	"DceLimitTimeShopInfo","0",
	"DceLimitTimeShopBuy","1",
	"DceComposeSouls","0",
	"DceSoulPieceList","0",
	"DcePlotCopyWarEnter","0",
	"DcePlotCopyWarMove","1",
	"DcePlotCopyWarRoll","1",
	"DcePlotCopyBattleInfo","0",
	"DceActivateTalent","0",
	"DceUpgradeTalent","0",
	"DceTalentList","0",
	"DcePlotCopyWarOpen","0",
	"DceAutoUpgradeScience","0",
	"DceGlobalArenaData","0",
	"DceGlobalArenaSignUp","1",
	"DceGLobalArenaPlayOffList","0",
	"DceGLobalArenaSelfInfo","0",
	"DceGlobalArenaBattleProgress","0",
	"DceGlobalArenaBattle","0",
	"DceGlobalArenaUpdateTactic","1",
	"DceGlobalArenaEncourage","1",
	"DceGlobalArenaBack","0",
	"DceGlobalArenaProstrate","1",
	"DceGlobalArenaChamption","0",
	"DceSaluteData","0",
	"DceSalute","0",
	"DceGoldLeaderInfo","0",
	"DceGoldLeaderGetOrder","0",
	"DceGoldLeaderBuyOrder","0",
	"DceGoldLeaderExplore","0",
	"DceBuyLuckyGodItem","0",
	"DceUpgradeSeiko","0",
	"DceRemouldSeiko","0",
	"DceEquipSeiko","0",
	"DceUnEquipSeiko","0",
	"DceAutoEquipSeikoSoldier","0",
	"DceForgeSeiko","0",
	"DceSaveForge","0",
	"DceComposeSeiko","0",
	"DceRedcutionSeiko","0",
	"DceDecomposeSeiko","0",
	"DceSetTacticForStageTower","0",
	"DceEnterStageTower","0",
	"DceStageTowerPurchaseAndResurr","1",
	"DealDceFindEnemyForStageTower","0",
	"DealDceSeikoShopHandle","0",
	"DceShipLockOpt","0",
	"DcePaperLockOpt","0",
	"DceCaptainLockOPt","0",
	"DceRenameGuild","0",
	"DceChat","0",
	"DceChatData","0",
	"DceRankList","0",
	"DceSoulLockOpt","0",
	"DcePartsLockOpt","0",
	"DceSeikoLockOpt","0",
	"GoldIslandCancelHelp","0",
	"DceGlobalArenaCheckEncourage","0",
	"DceGuildBattleAuto","0",
	"DceStageTowerReset","1",
	"DceSeikoExchange","1",
	"DceWeal","1",
	"DceRechargeBackGift","1",
	"DceAutoEquipSoul", "0",
	"DceUnAutoEquipSoul", "0",
	"DceGlobalGuildBattleSign","1",
	"DceGlobalGuildBattleAdjust","1",
	"DceGlobalGuildBattleEncourage","1",
	"DceGlobalGuildBattleUpdate","0",
	"DceGlobalGuildBattleData","0",
	"DceGlobalGuildBattleProstrate","1",
	"DceGlobalGuildBattleChamption","0",
	"DceScoutGuild","0",
	"DceWechatShare","0",
	"BATTLE_STAGE",	"1",
	"BATTLE_STAGE_SWEEP", "1",
	"BATTLE_ADVSTAGE",	"1",
	"BATTLE_ADVSTAGE_SWEEP", "1",
	"BATTLE_ARENA",	"1",
	"BATTLE_TREASURESTAGE",	"1",
	"BATTLE_GUARD_STAGES", "1",
	"BATTLE_ROBBERY", "1",
	"BATTLE_ROBBERY_SWEEP", "1",
	"BATTLE_TYPE_ARMADA", "1",
	"BATTLE_TYPE_STAGETOWER", "1",
	"BATTLE_TYPE_CAMPBATTLE","0",
	"PROP_ADD", "1",
	"PROP_COST", "1",
	"PARTS_ADD", "0",
	"PARTS_COST", "0",
	"PARTPIECE_ADD", "0",
	"PARTPIECE_COST", "0",
	"PAPER_ADD", "0",
	"PAPER_COST", "0",
	"PAPERPIECE_ADD", "0",
	"PAPERPIECE_COST", "0",
	"SHIP_ADD", "0",
	"SHIP_COST", "0",
	"MAIL_ADD", "0",
	"MAIL_COST", "0",
	"USE_VIRTUALPROP", "0",
	"BROADCAST", "1",
	"STAT_PARTS_UPGRADE",	"0",
	"STAT_PARTS_REMOULD",	"1",
	"STAT_SHIP_UPGRADE",	"0",
	"STAT_SHIP_REMOULD",	"1",
	"STAT_SKILL_UPGRADE",	"1",
	"STAT_GET_RECHARGE_REWARD", "1",
	"STAT_GET_RECHARGE_REWARD_FUNC", "1",
	"STAT_MEDAL_STARCOPY",	"0",
	"STAT_RICHEST_AWARD", "1",
	"STAT_GHOSTSHIP_AWARD", "1",
	"STAT_LIMITSHIP_AWARD", "1",
	"STAT_CAMPBATTLE_AWARD", "1",
	"STAT_COST_REWARD", "1",
	"STAT_UNIFYUSERGUILDID","0",
	"STAT_LIMITCAPTAIN_AWARD,","0",
	"GUILD_MEMBERLIST",	"0",
	"GUILD_CREATE", "0",
	"GUILD_DELETE", "0",
	"GUILD_ADDMEMBER", "0",
	"GUILD_DELMEMBER", "0",
	"ROBBERY_PLAYER", "0",
	"ROBBERY_NPC", "0",
	"STAT_FRIENDSYS_BACKSENDELEC","0",
	"AWARDCENTER_ADD", "0",
	"STAT_LUCKY_WHEEL_REWARD","1",
	"SOUL_ADD","1",
	"SOUL_PAPER_OPEN","0",
	"SOUL_COST","1",
	"MISTERYSHOP_REFRESH", "1",
	"MISTERYSHOP_BUY", "1",
	"CAMPBATTLESCORE_ADD", "1",
	"MORALE_COST", "0",
	"CAMPBATTLE_RESULT", "1",
	"CAMPBATTLE_ATTACK", "1",
	"CAMPBATTLE_OCCUPY", "1",
    "LUCKYCAT_DATA_REQUEST","0",
    "LUCKYCAT_REQUEST","1",
    "RECHARGESEVENDAY_DATA_REQUEST", "0",
    "RECHARGESEVENDAY_REQUEST", "1",
    "CHRITMAS_LOTTERY","1",
    "CHRITMAS_LOTTERY_TOKEN_EXCHANGE", "1",
    "TOKEN_ADD", "1",
    "TOKEN_DEC", "1",
    "BONUS_FLY_DATA_REQUEST", "0",
    "BONUS_FLY_REQUEST", "1",
	"STAT_AUTOCHANGECHIEF","0",
	"STAT_GUILDSENDMAIL","0",
    "CHRITMAS_LOTTERY_SCORE_EXCHANGE","1",
    "MONTH_SIGN_TAKE","1",
    "VALENTINE_DATA_REQUEST","0",
    "VALENTINE_GIVE_GIFT","1",
    "ONEARMEDBANDIT_DATA","0",
    "ONEARMEDBANDIT_TAKE", "1",
    "ONEARMEDBANDIT_TOP_AWARD","1",
    "PAYUSER_ADDCASH","1",
    "PAYUSER_COSTCASH","1",
    "PAYUSER_LOGIN","1",
    "PAYUSER_LOGOUT","1",
    "PLAYERADDPRETIGE","1",
    "PLAYERCOSTPRETIGE","1",
    "CHALLENGE_ACTION", "1",
    "CHALLENGE_BUY", "1",
    "CHALLENGE_CHAMPION", "0",
    "CHALLENGE_DATA_REQUEST", "0",
    "CHALLENGE_ENEMY_DATA", "0",
    "CHALLENGE_FIGHT_DATA", "0",
    "CHALLENGE_RANK", "0",
    "CHALLENGE_REFRESH", "0",
    "CHALLENGE_REVENGE", "0",
    "CHALLENGE_SIGN_UP", "1",
    "CHALLENGE_WORSHIP", "1",
    "CHALLENGE_SEND_REWARD", "1",
    "CHALLENGE_REFRESH_CHARGE","1",
	"CAPTAIN_ADD","0",
	"CAPTAIN_DEL","0",
	"CAPTAINPIECE_ADD","0",
	"CAPTAINPIECE_COST","0",
	"JUNIORCAPTAIN_ADD","0",
	"JUNIORCAPTAIN_DEL","0",
	"SENIORCAPTAIN_ADD","0",
	"SENIORCAPTAIN_DEL","0",
	"STAT_UPGRADECAPTAIN","0",
	"STAT_PROMOTECAPTAIN","0",
	"STAT_FIRECAPTAIN","0",
    "AddExploit", "1",
    "CostExploit","1",
    "SOUL_PROMOTE", "0",
    "SOUL_DECOMPOSE", "0",
    "SOUL_RESTORE", "0",
	"STAT_ADDGUILDSINGCONTRIBUTE","0",
	"STAT_GUILDBATTLEPRODUCEPOINTS","0",
	"STAT_GUILDBATTLE_AWARD","0",
	"GUILDBATTLE_MORALDE_COST","0",
	"GUILDBATTLE_SCORE_ADD","0",
	"GUILDBATTLE_ATTACK","0",
	"GUILDBATTLE_OCCUPY","0",
	"ChangeRole","0",
	"GOLD_ISLAND_DEL","0",
	"GOLD_ISLAND_ADD","0",
	"GOLD_ISLAND_AWARD","0",
	"STAT_ARMADA_AWARD","0",
	"SOULPIECE_ADD","0",
	"SOULPIECE_COST","0",
	"GET_EVERYDAY_TASK_REWARD","0",
	"ADD_EVERYDAY_TASK_FINISHED_TIMES","1",
	"TALENT_ADD","0",
	"TALENT_ACTIVE","0",
	"TALENT_UPGRADE","0",
	"STAT_VALENTINE_AWARD","0",
	"GOLD_LEADER_RANK_AWARD","0",
	"STAT_SEIKO_UPGRADE","0",
	"STAT_SEIKO_REMOULD","0",
	"SEIKO_COST","0",
	"SEIKO_ADD","0",
	"SEIKOPIECE_COST","0", 
	"SEIKOPIECE_ADD","0",
	"Ship_Resurrection","0",
	"Seikoshop_Refresh","0",
	"STAT_TICKGOLDLEADER","0",
	"SynStage2World","0",
	"MissSynStage2World","0",
	"PrintStageEnemy","0",
	"ONEARMEDBANDIT_TEN","0",
	"TuanGouInfo", "0",	
	"TuanGouOpt", "1",	
	"TuanGou_JoinGift", "1",
	"TuanGou_NJoinGift", "1",
	"TuanGou_BuyItems", "1",
	"TuanGou_Global", "1",
	"SeikoScore", "0",
	"FIRSTRECHANGE_GIFT", "1",
	"STAT_TICKGOLDLEADER2","0",
	"GlobalGuildBattleGame","1",
	"PROMOTEBATTLE","0",
	"DIVIDEGUILD","0",
};

const char* log_string(int log_type)
{
    if (log_type < 0 || log_type >= LT_MAX)
    {
        return "WrongType";
    }

    return LOG_CONFIG[log_type*2];
}

bool log_sampling(int log_type)
{
    if (log_type < 0 || log_type >= LT_MAX)
    {
        return true;
    }

    return LOG_CONFIG[log_type*2+1][0] == '1';
}

